### ISSUE TITLE
Working with Relay and react-rails.

### ISSUE THREAD

**Issue by gl2748** [reactjs/react-rails#709] opened 2017-05-11 14:49 UTC
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [x] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

-------
## Fundamental question:
Does the react_component() method supplied by this gem support Relay Containers?

I see this: https://github.com/gauravtiwari/relay-rails-blog/blob/blog/part3/app/assets/javascripts/react_relay_ujs.js

And am wondering if this has been resolved?

### Background / 'What exactly do you mean'?
I've been tasked with working Relay into a Rails app that already has some react integration and a graphQL back end.

It's using Browserfiy, and this `react-rails` gem.

I'm not massively familiar with Rails and have been struggling through this for a few days. Happy to hear of more performant and contemporary approaches, including how this would work on Rails 5.1

Suffice to say my issue is as follows.

> test.html.erb
```
<%= react_component('RelayTestApp`, {
      test: {
        hello: "world",
      },
  }, { class: 'relay-test' }) %>
```

> main.js
```
//= require_self
//= require react_ujs
//= require react-rails-hot-loader

require('babel-polyfill');

var React = window.React = require('react');
var ReactDOM = window.ReactDOM = require('react-dom');
var Relay = window.Relay = require('react-relay');

const RelayTestApp = window.RelayTestApp = global.RelayTestApp = require('./RelayTestApp.jsx');
```

> RelayTestApp.jsx

 ```
import React from 'react';
import Relay from 'react-relay';
import ReactDOM from 'react-dom';
import RelayTest from './components/RelayTest.jsx';
import RelayTestRoute from './routes/RelayTest.jsx';

const RelayTestApp = () => {
  ReactDOM.render(
    <Relay.RootContainer
      Component={RelayTest}
      route={RelayTestRoute}
    />,
    document.getElementById('relay-test')
  );
};

module.exports = RelayTestApp;
```

> Get this error:
```
Warning: _renderNewRootComponent(): Render methods should be a pure function of props and state; triggering nested component updates from render is not allowed. If necessary, trigger nested updates in componentDidUpdate. Check the render method of m.
```

**Comment by alkesh26** [comment] 2022-11-10 18:01
@gl2748 Were you able to resolve the issue? Closing this one. Feel free to create a new one if the issue is not resolved.

**Closed by alkesh26** 2022-11-10 18:01 UTC
