### ISSUE TITLE
0.12.2.0 version -- how to do i8n at all?

### ISSUE THREAD

**Issue by rstudner** [reactjs/react-rails#158] opened 2015-02-01 15:25 UTC
How can I do any sort of t('') i8n stuff with this?

I can't seem to put a _someTemplate.js.jsx.erb into the views folder (the jsx compilation only seems to take place in assets/javascripts etc)

Just not sure how to use React w/ templates (which would require i8n in any real app) via this gem etc

(note -- just doing pure JS/templates that will never require server side templating of any kind works fine)

Thoughts?

**Comment by danott** [comment] 2015-02-02 21:40
There was a [great talk](https://www.youtube.com/watch?v=Sla-DkvmIHY&list=PLb0IAmt7-GS1cbw4qonlQztYV1TAW0sCr&index=10) at React.js Conf this past week on this very topic.

In the specifics of rails, I'd imagine having some kind of `store` that holds your translations, then referencing those by key in your components.

**Comment by danott** [comment] 2015-02-02 21:47
@rmosolgo we can probably move this conversation to https://github.com/reactjs/react-rails/issues/128

**Comment by rmosolgo** [comment] 2015-02-02 22:13
closed as duplicate of #128

**Closed by rmosolgo** 2015-02-02 22:13 UTC
