### ISSUE TITLE
React Rails + Turbolinks not working correctly on initial page load

### ISSUE THREAD

**Issue by edwardmp** [reactjs/react-rails#767] opened 2017-08-10 18:13 UTC
- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [x] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

-------

Hi, I've used this gem for a while now and it's great. However, these last few months I've ran into an issue I can't really explain.

What I noticed at some point is that the React state somehow isn't loaded correctly by the components that are mounted. The odd thing is that this only happens when this page is the first page I load. So If open a new browser window, load this page, then the issue would occur. If I then navigate to another page on my site and navigate back to the problematic page everything works fine.

I managed to track this issue down to occurring since v2 of this gem. I resorted back to the last v1 version of this gem (1.11.0) and this issue doesn't display there. When I upgrade to v2.1.0 then I encounter this issue, 2.2.1 also displays the issue. I am not able to test against any earlier v2 versions since I use Rails 5.1.

I suspect this might have something to do with Turbolinks.

**Comment by BookOfGreg** [comment] 2017-10-25 09:45
Hi @edwardmp 

Sorry for taking so long to get to these issues, just categorising and organising them so I can start working down the open issues list.
Is #772 a duplicate of this?
Also does this still occur?

**Comment by BookOfGreg** [comment] 2018-02-06 09:06
I believe this to be fixed in #868 (Pre-release if you want to test it)
@edwardmp I'll reopen if this does not fix it for you. Thanks for the report 👍

**Closed by BookOfGreg** 2018-02-06 09:06 UTC
