### ISSUE TITLE
Webpacker 4.x support

### ISSUE THREAD

**Issue by shaundr** [reactjs/react-rails#939] opened 2018-10-03 21:05 UTC
Webpacker's master branch is at 4.0.0.pre.3

The readme here states that there is support for Webpacker 3.x, 2.x, 1.1+

Are there plans to support 4.x? I do not see any open issues or branches.

**Comment by ttanimichi** [comment] 2018-10-04 03:36
Can you take a look at #918?

Duplicate of #918

**Closed** 2018-10-04 03:36 UTC
