### ISSUE TITLE
What I work ajax with react and rails?

### ISSUE THREAD

**Issue by marcosvicente** [reactjs/react-rails#657] opened 2017-01-18 23:37 UTC
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

-------

(Describe your issue here)

**Comment by akshaymohite** [comment] 2017-02-09 17:06
@marcosvicente this seems to be a duplicate of #656, can this be closed?

**Comment by rmosolgo** [comment] 2017-02-09 18:30
Yep, thanks for providing that link in #656!

**Closed by rmosolgo** 2017-02-09 18:30 UTC
