### ISSUE TITLE
ReactRailsUjs.components is empty

### ISSUE THREAD

**Issue by TB-Development** [reactjs/react-rails#1267] opened 2023-04-18 19:46 UTC
### Expected behavior
I want the react component to render content on the screen

### Actual behavior
Components are not mounting at all.  There is no response from `componentDidMount()` react function inside the component, but I see the component on the screen, but with nothing that the `render` call would print.

### System configuration

Ruby: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
Rails: 4.2.11.3
Webpacker: 4.3.0
Sprockets: 3.7.2
Node: v14.21.3
Yarn: 1.22.19
react-rails: 2.6.2

-------

I'm working on integrating React into Rails using webpacker.  Webpacker is responsible for only React in this application, sprockets will load the rest.   I've recently upgraded to Rails 4.2.11.3 from the latest version of Rails 3.  Rails 3 doesn't support Webpacker, and there are ES6 issues with Sprockets and React, so I've decided it's best to use Webpacker to manage React.

I've followed several tutorials in setting up React with Webpacker, this is [the best one I've found ](https://blog.kiprosh.com/integrating-react-with-rails/).  

Please reference this [SO post](https://stackoverflow.com/questions/76048008/react-component-render-call-loaded-by-webpacker-isnt-rendering-anything-after-r) for extra information

I'm not getting any console errors, but when I list the components that ReactRailsUjs has mounted, it returns `{}`.  So I'm a bit confused here, why are the components not mounting?  It seems like I've done everything the guides say.

![Screen Shot 2023-04-18 at 3 47 34 PM](https://user-images.githubusercontent.com/75102760/232889234-1de7fe0a-ca86-443d-bd91-e2c0f8e0076d.png)
![Screen Shot 2023-04-18 at 3 47 23 PM](https://user-images.githubusercontent.com/75102760/232889242-f69a3339-db8a-4f3a-ba33-24d4407662f1.png)

**Comment by ahangarha** [comment] 2023-04-19 09:57
May you create a public repo to demonstrate and reproduce the issue? This way, we can help more effectively, mainly since your setup uses outdated Rails and Webpacker.

**Comment by ahangarha** [comment] 2023-06-21 10:29
@TB-Development May you please share some updates? Could you resolve the issue?

I close the issue for now. We can open it again if this issue persists and you can help us to reproduce it.

**Closed by ahangarha** 2023-06-21 10:29 UTC
