### ISSUE TITLE
[react-rails] Cannot find component for element

### ISSUE THREAD

**Issue by alebian** [reactjs/react-rails#713] opened 2017-05-12 16:34 UTC
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [x] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

-------

Hi,

I wanted to try the gem and in development everything works fine but in production I get this error:
```
[react-rails] Cannot find component: 'Title' for element ...
```
The component is a very simpĺe one:
```
class Title extends React.Component {
  render() {
    return (<h1>{this.props.text}</h1>);
  }
}
```
I followed all the instructions in the README (added all the "requires" in files), I also read and followed other people's solutions to the same problem by adding config.react.variant = :production.

I believe that the problem comes after the assets minification. In the application.js minified I can see a Test function being defined but I think it might be in a different scope that the gem expects.

My Gemfile is [this](https://gist.github.com/alebian/afb290c1d0fa25e8228c112aeb6ac1be#file-gemfile) and my Gemfile.lock is [this](https://gist.github.com/alebian/afb290c1d0fa25e8228c112aeb6ac1be#file-gemfile-lock)

Thanks!

**Comment by kyleknighted** [comment] 2017-05-12 17:48
Update your component code to include the import for React and export the module.

```es6
import React from 'react';

class Title extends React.Component {
  render() {
    return (<h1>{this.props.text}</h1>);
  }
}

export default Title;
```

**Comment by alebian** [comment] 2017-05-16 13:05
@kyleknighted That raises this error in development:

    Uncaught ReferenceError: exports is not defined

And of course after:

    [react-rails] Cannot find component: 'Title' for element

**Comment by rmosolgo** [comment] 2017-05-16 14:08
Your error includes `exports`, but I don't see that word in the example code above. Can you post the file which gives you the `ReferenceError`?

**Comment by alebian** [comment] 2017-05-16 14:16
@rmosolgo The code is this:

```
import React from 'react';

class Title extends React.Component {
  render() {
    return (<h1>{this.props.text}</h1>);
  }
}

export default Title;
```

As @kyleknighted told me to try

**Comment by kyleknighted** [comment] 2017-05-16 14:39
You could try giving this a shot. 

open up `config/webpack/loaders/react.js` and change it to
```es6
module.exports = {
  test: /\.(js|jsx)?(\.erb)?$/,
  exclude: /node_modules/,
  loader: 'babel-loader',
  query: {
    presets: ['react', 'es2015', 'stage-2']
  }
}
```
and also
`yarn add babel-preset-es2015 babel-preset-react babel-preset-stage-2`
and then restart your webpack compiler

**Comment by alebian** [comment] 2017-05-16 16:01
@kyleknighted the filename is title.js.jsx also I don't have webpacker installed because it is a legacy application that I upgraded to Rails 4.2. Do I need to install webpacker?

**Comment by rmosolgo** [comment] 2017-05-16 18:01
Sprockets doesn't support Nodejs modules, so the code above is for webpacker only. 

I think your first hunch is correct, it's a problem caused by minification. Uglify 3.1 minifies top-level identifiers by default, see: https://github.com/reactjs/react-rails/issues/668#issuecomment-283791307

I see your gemfile.lock has uglify 3.2, could you try reverting to 3.0 ?

**Comment by alkesh26** [comment] 2022-10-31 11:36
@alebian, Do we have any updates on this? If the issue persists, we can reopen this. Closing this for now.

**Closed by alkesh26** 2022-10-31 11:36 UTC

**Comment by almyasheva-venera** [comment] 2023-02-16 08:23
I got the same problem.
This https://github.com/reactjs/react-rails/blob/master/README.md#3-install-react-and-some-other-required-npm-packages helps me.

Take a look at your package.json and add babel configuration
Also update the Babel configuration in the package.json file:

"babel": {
  "presets": [
-   "./node_modules/shakapacker/package/babel/preset.js"
+   "./node_modules/shakapacker/package/babel/preset.js",
+   "@babel/preset-react"
  ]
},
