### ISSUE TITLE
div without data-react-props when prerender: true

### ISSUE THREAD

**Issue by stereodenis** [reactjs/react-rails#408] opened 2015-11-20 13:42 UTC
Is it possible not to render content in wrapper div in data-react-props when prerender: true ?

**Comment by rmosolgo** [comment] 2015-11-24 14:16
I'm open to this! Maybe if you pass `prerender: true, tag: nil`? 

You can see the relevant code here: https://github.com/reactjs/react-rails/blob/master/lib/react/rails/component_mount.rb#L24

**Comment by stereodenis** [comment] 2015-11-24 18:22
@rmosolgo tag: nil not working as expected...

**Comment by rmosolgo** [comment] 2015-11-24 18:37
Yes, you'd have to implement it :)

**Comment by stereodenis** [comment] 2015-11-24 21:48
@rmosolgo I made this, but it breaks js behavior of the component
when i tried to add `data-react-class` to root div of component I get this 
http://take.ms/Mfo0d
![expotrade 2015-11-25 00-46-04](https://cloud.githubusercontent.com/assets/1406461/11381617/22bf6d96-930e-11e5-8f00-ad930d1a5a70.png)

**Comment by stereodenis** [comment] 2015-11-25 12:56
@rmosolgo get some results (:
I'm front-end developer so I still need some help

**Comment by drewhamlett** [comment] 2015-11-29 23:30
I think he's asking this

```
<%= react_component('Chart', {}, prerender: true) %>
```

**Comment by stereodenis** [comment] 2015-11-30 08:43
@drewhamlett 
Now we have content duplication (data-react-props and component html)
It is not good for SEO

**Comment by panasyuk** [comment] 2016-01-18 10:17
@stereodenis Please take a look at this. I'm now trying to make it more convenient to use.
https://github.com/panasyuk/react-rails-view_helper_implementation

**Comment by alkesh26** [comment] 2022-10-31 08:28
It seems like the issue is resolved in https://github.com/panasyuk/react-rails-view_helper_implementation. Let's close this. We can reopen if needed.

**Closed by alkesh26** 2022-10-31 08:28 UTC
