### ISSUE TITLE
How to get image paths in JSX?

### ISSUE THREAD

**Issue by jongbeau** [reactjs/react-rails#211] opened 2015-03-16 14:32 UTC
Is there a way to use rails helpers like asset_path in JSX? If not, what is the best practice for accessing image paths?

**Comment by ericdfields** [comment] 2015-03-16 21:00
Typically you've been able to name your file 'my_script.js.erb' and then call interpolated ruby in your code:

````javascript
var image_path = "<%= asset_path(my_image.png) %>"
````

I don't see why my_script.js.jsx.erb wouldn't work!

**Comment by ericdfields** [comment] 2015-03-16 21:01
Might also be `#{asset_path(my_image.png)}`… that's what it was when I was writing coffee, but I assume that was coffeescript syntax.

**Comment by bogdan-dumitru** [comment] 2015-03-16 21:07
This depends a lot on your stack. What @ericdfields works if you're compiling JSX inside of the rails asset pipeline. If you're using browserify or webpack it's not as straightforward. In the case of browserify what I did for a while is a have a [custom preprocessor](https://mackuba.eu/2012/05/06/extending-asset-pipeline-with-custom-preprocessors/) for the build and a convention to signal that this needs to be processed like:

```javascript
// ...
render: function() {
  return (
    <img src="%image_path(some_asset_that_rails_knows.png)%" />
  )
}
// ...
```

This way I would use my custom preprocessor to match ``/%([a-z]*)_path\((.*)\)%/`` and use the proper rails helper with the argument to generate the full asset path and replace that in the build JS.

Nowadays we just use webpack to mange all our frontend assets and it's awesome. Long gone are the days of sprockets :).

**Comment by ericdfields** [comment] 2015-03-16 21:10
@bogdan-dumitru that sort of preprocessing was a blocker at fully converting our stack to webpack. Thanks for sharing. Still basically running a separate webpack process on dev and then having a compilation step for prod via CI or similar? There's still some gaps in the webpack<>sprockets<>rails relationship in my head.

**Comment by jongbeau** [comment] 2015-03-16 22:44
I'm using ES6 and commonJS so I use browserify to do the compiling. Renaming to script.js.jsx.erb was the first thing that I tried and it did not work. Currently, i'm working around this by using a CSS style that sets the content-url. asset_path works fine in the CSS with sprockets.

I have been looking into webpack recently due to the react hot reload feature. How are things working out as a full replacement of sprockets?

**Comment by bogdan-dumitru** [comment] 2015-03-17 06:19
It's going really good so for, minus some small snafus due to node instability (because of all the moving parts/dependencies). But it's really interesting. I'm working on a blog post about this so I'll keep you guys posted.

**Comment by vipulnsward** [comment] 2015-03-17 06:22
I do what @jongbeau mentioned. Setting a url from style is easier and cleaner.
Another way is passing around the values from data attributes, or generated and passed from props.
In later case, helpers are freely available when generating props, so it shouldn't be an issue.

**Comment by andyyou** [comment] 2015-06-02 05:09
Thanks @ericdfields , I also think if you are using `react-rails` that its a easiest way to solve this problem.

**Comment by honki91** [comment] 2015-07-17 04:28
@bogdan-dumitru Did you end up writing that blog post? I'd be interested in learning about your experience.

**Comment by andyyou** [comment] 2015-07-20 00:15
In fact, it's just a bit trick and not prefect solution, I thought. You can append extension `.erb` to js(jsx) file and then you can use the ability of erb, but not all of helpers you can use.

**Comment by mikesea** [comment] 2015-08-13 22:29
If you're just using the asset pipeline, I found a solution.

This does not work:
```js
render: function() {
  return (
    <img src="<%= asset_url('path/to/image.png') %>" />
  )
}
```

This did work (wrap the src prop in braces):
```js
render: function() {
  return (
    <img src={"<%= asset_url('path/to/image.png') %>"} />
  )
}
```

**Comment by j0214ack** [comment] 2015-08-28 01:55
Why not 

```js
render: function() {
  return (
    <img src={this.props.img_src} />
  )
}
```

and then

```ruby
render_component('Component', img_src: image_url('the_path'))
```

this way also makes the component more reusable I suppose

**Comment by bcardiff** [comment] 2015-09-24 15:35
@mikesea suggestion works, but since I am using es6 the file needed to be named `*.es6.jsx.erb`. And the enclosing `{...}` were not needed.

```
class MyImage extends React.Component {
  render () {
    return (
      <img src="<%= asset_url('path/to/image.png') %>" />
    );
  }
}
```

**Comment by PaulBrunache** [comment] 2015-12-17 00:39
you guys are awesome ! I was ripping my hair trying to figure this out

**Comment by chalmagean** [comment] 2016-01-19 15:15
Another thing you might prefer is to pass down the asset paths as props, or just use a global object that holds the paths to every asset.

That might look something like this:

```ruby
# app/controllers/some_controller.rb
def some_action
  @images = {
    oneIcon: path_to_asset('one_icon.png'),
    twoIcon: path_to_asset('two_icon.png')
  }
end

private

  def path_to_asset(asset)
    ApplicationController.helpers.asset_path(asset)
  end
```

```ruby
# app/views/some_controller/some_action.html.erb
<%= tag :div, data: { images: @images }, id: "root" %>
```

```javascript
# app/assets/javascripts/app.js.jsx
var rootElement = document.getElementById("root");
var imagePaths = JSON.parse(rootElement.dataset.images);

window.ReactDOM.render(
  <MainComponent imagePaths={imagePaths} />
  rootElement
);
```

**Comment by pioz** [comment] 2016-02-01 14:49
In my `app/assets/javascripts/components/navbar.js.jsx.erb` I can write something like this:
```
    render() {
      return(
        <div className="navbar-header">
          <button className="navbar-toggle collapsed" data-target="#navbar-collapse" data-toggle="collapse" type="button">
            <span className="sr-only">
              <%= I18n.t('menu.toggle_navigation') %>
            </span>
            <span className="icon-bar"></span>
            <span className="icon-bar"></span>
            <span className="icon-bar"></span>
          </button>
          <ul>
            <li>
              <%= link_to root_path, className: 'navbar-brand' do %>
                <span className='glyphicon glyphicon-home'></span>
                &nbsp;
                <%= I18n.t('menu.now') %>
              <% end %>
            </li>
            <li><%= link_to I18n.t('menu.archive'), archive_path%></li>
          </ul>
        </div>
      );
    }
```
All works fine except for the link_to with block... I have a syntax error: `syntax error, unexpected keyword_end, expecting ')'`
If I remove the block all works fine.
Any idea?

**Comment by bcardiff** [comment] 2016-02-01 18:43
@pioz not sure, but probably you reach something erb vs rails-erb around http://www.timelessrepo.com/block-helpers-in-rails3 . You may try to use a block with `{ ... }` in the `link_to` instead of breaking it in multiple `<% %>`.

But that is just the tip of the iceberg. Rails helpers output html and not jsx-html. So `class`/`className`. `for`/`htmlFor`, etc attributes need to be translated. And you won't be able to use interpolation with jsx expression `attr={...}`, since they will be quoted `attr="{...}"`. Knowing that, if those restriction are fine, go for it :-)

**Comment by gwong89** [comment] 2016-02-12 10:24
so if im compiling with webpack, which solution from these posts would work?

**Comment by varun-raj** [comment] 2016-03-01 05:53
Store it in a JS variable and use it

**Comment by TxsAdamWest** [comment] 2016-09-11 16:37
I am having an issue with the src path...  Console reads a bunch of 404 errors for each of the img's.  Is there something wrong with my formatting or pathing ?  	    

<img src={'../images/jesseleach.jpg'} />

![screen shot 2016-09-11 at 11 35 44 am](https://cloud.githubusercontent.com/assets/16004559/18418863/edb55cdc-7813-11e6-8869-44413e8712d6.png)

**Comment by varun-raj** [comment] 2016-09-12 06:26
@TxsAdamWest are you using it in a rails project?

**Comment by TxsAdamWest** [comment] 2016-09-12 14:08
No,  JavaScript.    I think what I was doing wrong was the img src paths
needed to be in curly braces.  They wouldn't read otherwise..

On Sep 12, 2016 1:26 AM, "Varun Raj" <notifications@github.com> wrote:

@TxsAdamWest <https://github.com/TxsAdamWest> are you using it in a rails
project?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/reactjs/react-rails/issues/211#issuecomment-246259661>,
or mute the thread

**Comment by bcardiff** [comment] 2016-09-12 14:58
@TxsAdamWest the problem is that the paths probably don't work from the url you are loading the scripts and that is why you get 404. This whole thread is about rendering absolute paths in the views that in production will have the fingerprint. You are using relative paths, that although it might seems right from the actual file location, when rendering from `/` or `/:controller/:action` they will fail at least in one.

**Comment by vkhang55** [comment] 2016-09-20 23:52
This gem seems to solve that issue https://github.com/rainchen/react-rails-img/blob/master/vendor/assets/javascripts/react_rails_img.js.jsx.erb

**Comment by nextofsearch** [comment] 2016-11-10 03:37
Hi,

I am using Rails 5 with react-rails and browserify-rails gems and I can't figure out how to get image tag working. It seems that browserify-rails take precedence over .js files so there is no chance for Rails process .erb syntax in .js.jsx. Can someone help to use both gems and figure out how to use asset pipeline successfully?

**Comment by lakesare** [comment] 2016-12-08 08:06
Appending erb to form `js.jsx.erb` worked. Now I'm using ES6 and can use:

```
<section>
    <%= image_tag 'common/star.svg' %>
    {reviews}
</section>
```

**Comment by rmosolgo** [comment] 2016-12-09 21:58
Thanks for sharing all your solutions here! I don't think there's anything particularly required from this gem, so I'll close this issue.

**Closed by rmosolgo** 2016-12-09 21:58 UTC

**Comment by aurimus** [comment] 2017-03-12 02:30
My sprockets 4.0.0beta4 simply does not include the file (does not see it) if I change the ending to `.js.jsx.erb`, works fine with `js.jsx`. Any ideas?

**Comment by liamm12** [comment] 2018-01-05 23:07
If you have a few images you can just import it directly in your component like this

    import logo from './Pictures/1.jpg';
Then call it like this 

    <img src={logo} alt="logo" width={"240"} height={"240"}  />



If you want to get multi images like more than 50 img in own component, my own way to do that to specify each component has a `images.js` file,and then you can just import all the images that retarded of that component in `images.js` and  name it as the related component name 

 (It will let you know what this images file for.)

> As I prefer to keep all your images in `public` folder


images.js

    import logo from './images/logo.svg';
    import cover from './images/cover.svg';
    import profile from './images/profile.svg';
    import background1 from './images/body.svg';
    export default {
        logo,
        cover,
        profile,
        background1
    }

Then in your component you can just import `images.js file` like this, you can name it whatever you want

    import images from './images';
Then you can call any img you want like this

          <img src={images.logo} className="App-logo" alt="logo" />
          <img src={images.cover} className="App-logo" alt="logo" />
          <img src={images.profile} className="App-logo" alt="logo" />
          <img src={images.background1} className="App-logo" alt="logo" />

**Comment by devp-UditRaj** [comment] 2018-12-24 13:20
you can do this
<img src={require(`${this.props.**imagepath**}`)} alt="My Image"/>

and take **imagepath** as a prop in the tag and then pass it!!

**Comment by hiveer** [comment] 2019-01-30 08:50
What I have done is to import the image to JSX file like:
`import HeaderLogo from './header_logo.png';

then we can refer to it like this:

`<img src={HeaderLogo}>`

**Comment by nitzien** [comment] 2020-05-24 03:13
> My sprockets 4.0.0beta4 simply does not include the file (does not see it) if I change the ending to `.js.jsx.erb`, works fine with `js.jsx`. Any ideas?

@aurimus  Could you fix this? I am facing same problem.
