### ISSUE TITLE
You may have multiple copies of React loaded. 

### ISSUE THREAD

**Issue by vladi160** [reactjs/react-rails#833] opened 2017-11-04 16:10 UTC
I am using both server-side render component and client-side rendered. I have `server_rendering.js`:
`//= require react-server
//= require react_ujs
//= require ./components`

This is my `application.js`:
`//= require react
//= require react_ujs
//= require components`

and this is my view:
`<div id="react"></div>
<%= react_component('Post', {}, {prerender: true}) %>`

I am getting this error in the WEB console:

> You may have multiple copies of React loaded.

If I delete `server_rendering.js` client-side rendered component works fine. Otwerwise, server-side rendered component only works.

**Comment by BookOfGreg** [comment] 2017-11-04 16:46
That seems odd, is the `server_rendering.js` in the browser accidentally somehow?
I assume you are running Sprockets given the earlier issues.

**Comment by vladi160** [comment] 2017-11-04 17:19
I have no `sprockets` in `application.js`. The other strange things is if I remove:
`<%= react_component('Post', {}, {prerender: true}) %>`
- server-side element, client-side rendered element works fine. This from new created app.
If I remove `prerender` option, both components (server-side and client-side) works fine.

**Comment by BookOfGreg** [comment] 2017-11-04 17:45
Sorry I think I may have caused a misunderstanding there, sprockets is the name of the default asset pipeline in rails. If you aren't using webpacker, you are very likely using sprockets without knowing it's name.

I have a branch if the example app here: https://github.com/bookofgreg/react-rails-example-app/tree/sprockets
This should have a similar setup to the one you have, I'll check it runs with the latest version of the gem later, if possible could you try see what the difference is between what you have and that branch? It may help us reproduce the issue in server-side rendering.

**Comment by vladi160** [comment] 2017-11-04 21:49
Sry, yes I am using default assets pipeline, not Webpacker. I check your example app and there is error, too. Just create another component, but use it without gem helper and use both components one with gem helper (with option prerender) and another without gem helper. The problem comming from prerender option. This is the view:
`<div id="react"></div>
<%= react_component 'Post', { title: 'A working react component', body: 'Simple but effective' }, prerender: true %>`
and this is the component:
`class Main extends React.Component {
  render() {
    return <h1>Hello</h1>
  }
}

window.onload = function(){
  ReactDOM.render(<Main/>,document.getElementById('react'));	
}`
Without load event it is another error `ReactDOM is not defined`

**Comment by BookOfGreg** [comment] 2017-11-04 22:42
Maybe I'm misinterpreting what you said, I'm not seeing any issue with these files.

Main.js.jsx
```
class Main extends React.Component { render() { return <h1>Hello</h1> } }
```

Index.html.erb
```
<%= react_component 'Post', { title: 'A working react component', body: 'Simple but effective' }, prerender: true %>
<%= react_component 'Main', { }, prerender: false %>
<script type="text/javascript">window.onload = function(){ ReactDOM.render(<Main/>,document.getElementById('react')); }</script>
```

Can you make a branch from the example app, and Pull Request the changes you want to make, so I can see the issue?

**Comment by vladi160** [comment] 2017-11-04 23:41
This one is with multiple copies error [https://github.com/vladi160/example](https://github.com/vladi160/example) and requires database and Devise, sry :(. This one [https://github.com/vladi160/example02](https://github.com/vladi160/example02)  is with error `TypeError: Cannot read property 'createElement' of undefined`

**Comment by vladi160** [comment] 2017-11-05 00:22
This is your example [https://github.com/vladi160/example03](https://github.com/vladi160/example03), without `prerender option` works fine

**Comment by BookOfGreg** [comment] 2017-11-05 13:43
In your first example, I couldn't help but notice [this line](https://github.com/vladi160/example/blob/master/config/initializers/assets.rb): `Rails.application.config.assets.paths << Rails.root.join('node_modules')`
If you want node modules, you probably want to be using Webpacker.

```bash
rails new example --webpacker=react
```

You also have `app/assets/frontend/components` as well as `app/assets/javascripts/components`. You should really only have one, and which one depends on the pipeline, I'd probably keep the 2nd and move the first's files in there.

You also have a `config/webpack/` folder so it looks like your assets have gotten mixed up somehow.

There's also a `bundle.js` file which looks like a webpacked bundle that probably has react in it.

You want to not load node_modules in sprockets, and not load the webpacked bundle, that that is at least 2 too many reacts loaded. Maybe there's more, I didn't dig further.

---

In example 2:
You're attempting to use JQuery in [MainTwo](https://github.com/vladi160/example02/blob/master/app/assets/javascripts/components/MainTwo.jsx#L7-L14)
That attempts to run client-side code server-side when `prerender: :true` and reactDom does not exist server-side, it's [React-dom-server](https://reactjs.org/docs/react-dom-server.html) that exists server-side.

So just move the code above into a normal JS location (maybe your `application.js` and delete the jquery reference server-side from here and it all works! https://github.com/vladi160/example02/blob/master/app/assets/javascripts/server_rendering.js#L1

---

In example 3:
Same again, trying to use JQuery server-side.

If you really must use something that depends on `document` or `window` server-side, fake it with one of the several global var packages, or do a presence check on `window` before trying to use it.
Wish there was a good blog post about server-side  variables out there but in general you can't depend on anything you haven't defined server-side, there is no browser.

**Comment by BookOfGreg** [comment] 2017-11-05 13:45
This was an interesting dive into the things that can go wrong when trying to use the gem, I'll see if I can generate a wiki page for these kinds of problems.
It's not an issue with this gem though so I'll add a documentation tag and close it when I get an article up.

This has been fun, thanks @vladi160, hope it all helps!

**Closed** 2017-11-07 16:14 UTC
Labels: discussion
