### ISSUE TITLE
Can't install it.. - Rails 4.2

### ISSUE THREAD

**Issue by dyatlov** [reactjs/react-rails#331] opened 2015-08-05 11:42 UTC
`rails g react:install`

```
/home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/react-rails-1.1.0/lib/react/rails/railtie.rb:42:in `block in <class:Railtie>': undefined method `version' for nil:NilClass (NoMethodError)
        from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `instance_exec'
```

**Comment by rmosolgo** [comment] 2015-08-05 15:47
Could you post your gemfile.lock? I think it's a conflict with a Sprockets/sprockets-rails version

**Comment by dyatlov** [comment] 2015-08-05 16:32
@rmosolgo sure: https://gist.github.com/dyatlov/07f9f68a02f6737aeb73

**Comment by vipulnsward** [comment] 2015-08-05 16:36
@dyatlov this is fixed on master. Can you give it a try?

**Comment by dyatlov** [comment] 2015-08-05 16:37
@vipulnsward thanks, trying

**Comment by dyatlov** [comment] 2015-08-05 17:11
@vipulnsward unfortunately,

vagrant@vagrant:/vagrant$ rails g react:install
/home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/react-rails-d433c0ddb103/lib/react/rails/engine.rb:5:in `block in <class:Engine>': uninitialized constant React::Rails::Engine::Sprockets (NameError)

**Comment by ncri** [comment] 2015-09-21 11:58
Same here, but a different error from one of my initiailizers. Seems a class loading issue, as that initializer works fine when loading the app normally. I will install manually...

**Comment by ncri** [comment] 2015-09-21 11:59
Btw.: To avoid name clashes I would call the folder rather react_components than components.

**Comment by ncri** [comment] 2015-09-21 12:02
One more thing: :) The generator assumes the manifest is called application.js. Not true for our projects. It is either application.js.coffee or application.js.coffee.erb here. Would be cool if the generator could also recognize those.

**Comment by ncri** [comment] 2015-09-21 12:11
Ah, turns out the generator error here is not limited to the generator.
In fact I cannot start up the app anymore after installing the gem:

```
/config/initializers/will_paginate.rb:3:in `<top (required)>': uninitialized constant WillPaginate::ActionView (NameError)
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/engine.rb:652:in `block in load_config_initializer'
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.2/lib/active_support/notifications.rb:166:in `instrument'
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/engine.rb:651:in `load_config_initializer'
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/engine.rb:615:in `each'
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/engine.rb:615:in `block in <class:Engine>'
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/initializable.rb:30:in `run'
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/nico/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /Users/nico/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/nico/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/nico/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/nico/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /Users/nico/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/initializable.rb:44:in `each'
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /Users/nico/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:413:in `call'
	from /Users/nico/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
	from /Users/nico/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/initializable.rb:44:in `each'
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /Users/nico/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:413:in `call'
	from /Users/nico/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
	from /Users/nico/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/nico/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /Users/nico/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /Users/nico/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/nico/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /Users/nico/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/application.rb:352:in `initialize!'
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/railtie.rb:194:in `public_send'
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/railtie.rb:194:in `method_missing'
	from /Users/nico/Rails/new_yousty/yousty/config/environment.rb:7:in `<top (required)>'
	from /Users/nico/Rails/new_yousty/yousty/config.ru:3:in `block in <main>'
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/rack-1.6.2/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/rack-1.6.2/lib/rack/builder.rb:55:in `initialize'
	from /Users/nico/Rails/new_yousty/yousty/config.ru:in `new'
	from /Users/nico/Rails/new_yousty/yousty/config.ru:in `<main>'
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/rack-1.6.2/lib/rack/builder.rb:49:in `eval'
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/rack-1.6.2/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/rack-1.6.2/lib/rack/builder.rb:40:in `parse_file'
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/rack-1.6.2/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/rack-1.6.2/lib/rack/server.rb:208:in `app'
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/commands/server.rb:61:in `app'
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/rack-1.6.2/lib/rack/server.rb:336:in `wrapped_app'
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/commands/server.rb:139:in `log_to_stdout'
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/commands/server.rb:78:in `start'
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/nico/.rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by ncri** [comment] 2015-09-21 12:18
Fixed it, had to include the will_paginate gem before the react-rails gem in the gemfile.

**Comment by rmosolgo** [comment] 2015-09-21 15:22
Wow, how strange! I never heard of an order dependency in a Rails Gemfile before!

**Comment by ncri** [comment] 2015-09-21 15:46
Yep, odd. But I did have it before. :) I think it probably has to do with what react-rails does when it is required. It seems to load my initializers - not every gem does that. And if the will_paginate gem is not loaded first, the initializer breaks.

**Comment by npverni** [comment] 2015-10-13 20:59
Seeing the same thing with `will_paginate`. Confirmed that changing the order fixes it.

**Comment by npverni** [comment] 2015-10-13 22:58
This looks like the commit that changed it https://github.com/reactjs/react-rails/pull/347.

Weird that we're both running into issues with `will_paginate`, so it could also be a `will_paginate` thing.

I've also been able to fix it by requiring in the will_paginate initializer:

```ruby
require 'will_paginate/view_helpers'
require 'will_paginate/view_helpers/action_view'
```

**Comment by ebenoist** [comment] 2015-10-25 14:23
I can confirm a similar load order issue with the mobile-fu gem.

**Comment by flowerett** [comment] 2015-11-23 13:51
Confirm similar issue with ```rolify``` gem
my gemfile:
```
rails (4.2.4)
react-rails (1.4.2)
rolify (4.0.0)
```
regarding to https://github.com/RolifyCommunity/rolify/issues/156 there's something wrong in the react-rails initializer

**Comment by rmosolgo** [comment] 2016-12-09 21:54
Sorry, it's been quite a while since I heard about an instance of this issue. If someone finds it again, please let me know and I'll see if any changes to our railtie can fix it!

**Closed by rmosolgo** 2016-12-09 21:54 UTC
